import bcrypt from "bcrypt";
const data = {
  users: [
    {
      name: "Rramirous",
      email: "rramirous@iduslocus.com",
      password: bcrypt.hashSync("Basirismygod", 8),
      isAdmin: true,
    },
    {
      name: "jhon",
      email: "jhon@email.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 0,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "2",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "3",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "4",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 0,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "5",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "6",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "7",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      countInStock: 10,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
  ],
};
export default data;
