const data = {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "2",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "3",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "4",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "5",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "6",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
    {
      _id: "7",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 120,
      brand: "xx",
      rating: 4.5,
      numReviews: 10,
      descrption: "high quality product",
    },
  ],
};
